stages:
#  - build
 - check

# variables:
#   DOCKER_BUILD_TAG: "stable"

.build-and-push:
  image: "docker:stable"
  stage: build
  when: manual
  tags:
   - docker
   - medium
  before_script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker info
  script:
   - docker build -t $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE:latest

danger-check:
  image:
    name: "registry.gitlab.com/hnbi/platform-as-a-service/test-projects/automate-code-review:latest"
    entrypoint: [ '/bin/sh', '-c' ]
  stage: check
  tags:
   - docker
   - medium
  cache: {}
  # rules:
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  #     when: always
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  #     when: always
  variables:
    ENV: "dev"
    ASSUME_ROLE: 'TRUE'
    HELM_DEPLOY_ACTION: "APPLY"
  script:
  - env
  - $PWD
