stages:
 - build
 - check

# variables:
#   DOCKER_BUILD_TAG: "stable"

# .common_rules: &common_rules
#   - if: $CI_DEFAULT_BRANCH != $CI_COMMIT_REF_NAME
#     when: never
  # - if: '$DANGER_REVIEW_DISABLED'
  #   when: never

build-and-push:
  image: "docker:stable"
  stage: build
  when: manual
  tags:
   - docker
   - medium
  before_script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker info
  script:
   - docker build -t $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE:latest

danger-check:
  image:
    name: "registry.gitlab.com/hnbi/platform-as-a-service/test-projects/automate-code-review:latest"
    entrypoint: [ '/bin/sh', '-c' ]
  stage: check
  tags:
   - docker
   - medium
  cache: {}
  rules:
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  #     when: always
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  #     when: always
  # - *common_rules
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: always
    # - if: '$CI_PIPELINE_SOURCE == $CI_DEFAULT_BRANCH'
    #   when: never

  variables:
    DANGER_GITLAB_HOST: "https://gitlab.com"
    DANGER_GITLAB_API_BASE_URL: "${CI_API_V4_URL}"
    DANGER_GITLAB_API_TOKEN: "${CI_JOB_TOKEN}"
    # : "${CI_MERGE_REQUEST_IID}"
  script:
  # - env
  - echo "$PWD"
  - ls -la
  - yarn danger ci
